[2025-04-24T21:17:12.175+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_prices_data_downloader_branching.branch_TCS.NS manual__2025-04-24T21:15:40.505356+00:00 [queued]>
[2025-04-24T21:17:12.188+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_prices_data_downloader_branching.branch_TCS.NS manual__2025-04-24T21:15:40.505356+00:00 [queued]>
[2025-04-24T21:17:12.189+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-04-24T21:17:12.214+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): branch_TCS.NS> on 2025-04-24 21:15:40.505356+00:00
[2025-04-24T21:17:12.228+0000] {standard_task_runner.py:60} INFO - Started process 4245 to run task
[2025-04-24T21:17:12.235+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'raw_prices_data_downloader_branching', 'branch_TCS.NS', 'manual__2025-04-24T21:15:40.505356+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/raw_price_data_testing.py', '--cfg-path', '/tmp/tmp01sdt8qk']
[2025-04-24T21:17:12.239+0000] {standard_task_runner.py:88} INFO - Job 229: Subtask branch_TCS.NS
[2025-04-24T21:17:12.301+0000] {task_command.py:423} INFO - Running <TaskInstance: raw_prices_data_downloader_branching.branch_TCS.NS manual__2025-04-24T21:15:40.505356+00:00 [running]> on host 8291240c5d79
[2025-04-24T21:17:12.408+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_prices_data_downloader_branching' AIRFLOW_CTX_TASK_ID='branch_TCS.NS' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T21:15:40.505356+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T21:15:40.505356+00:00'
[2025-04-24T21:17:12.410+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 233, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: prices_pipeline.<locals>.branch_condition() missing 1 required positional argument: 'ticker'
[2025-04-24T21:17:12.421+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=raw_prices_data_downloader_branching, task_id=branch_TCS.NS, execution_date=20250424T211540, start_date=20250424T211712, end_date=20250424T211712
[2025-04-24T21:17:12.435+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 229 for task branch_TCS.NS (prices_pipeline.<locals>.branch_condition() missing 1 required positional argument: 'ticker'; 4245)
[2025-04-24T21:17:12.486+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-24T21:17:12.517+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
