[2025-04-24T20:15:31.880+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_prices_data_downloader.clean_data__1 manual__2025-04-24T20:14:14.802249+00:00 [queued]>
[2025-04-24T20:15:31.887+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_prices_data_downloader.clean_data__1 manual__2025-04-24T20:14:14.802249+00:00 [queued]>
[2025-04-24T20:15:31.887+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-24T20:15:31.898+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): clean_data__1> on 2025-04-24 20:14:14.802249+00:00
[2025-04-24T20:15:31.907+0000] {standard_task_runner.py:60} INFO - Started process 1528 to run task
[2025-04-24T20:15:31.911+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'raw_prices_data_downloader', 'clean_data__1', 'manual__2025-04-24T20:14:14.802249+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/raw_price_data.py', '--cfg-path', '/tmp/tmpnhpo7dpf']
[2025-04-24T20:15:31.913+0000] {standard_task_runner.py:88} INFO - Job 200: Subtask clean_data__1
[2025-04-24T20:15:31.951+0000] {task_command.py:423} INFO - Running <TaskInstance: raw_prices_data_downloader.clean_data__1 manual__2025-04-24T20:14:14.802249+00:00 [running]> on host 8291240c5d79
[2025-04-24T20:15:32.037+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_prices_data_downloader' AIRFLOW_CTX_TASK_ID='clean_data__1' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T20:14:14.802249+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T20:14:14.802249+00:00'
[2025-04-24T20:15:32.039+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/raw_price_data.py", line 102, in clean_data
    df = pd.read_json(raw_json)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 733, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 818, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 858, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 713, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 451, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'int'>
[2025-04-24T20:15:32.050+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=raw_prices_data_downloader, task_id=clean_data__1, execution_date=20250424T201414, start_date=20250424T201531, end_date=20250424T201532
[2025-04-24T20:15:32.058+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 200 for task clean_data__1 (Invalid file path or buffer object type: <class 'int'>; 1528)
[2025-04-24T20:15:32.082+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-24T20:15:32.105+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
