[2025-04-24T21:03:42.499+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_prices_data_downloader_branching.branch_TCS.NS manual__2025-04-24T21:03:40.941634+00:00 [queued]>
[2025-04-24T21:03:42.507+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_prices_data_downloader_branching.branch_TCS.NS manual__2025-04-24T21:03:40.941634+00:00 [queued]>
[2025-04-24T21:03:42.507+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-24T21:03:42.520+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): branch_TCS.NS> on 2025-04-24 21:03:40.941634+00:00
[2025-04-24T21:03:42.529+0000] {standard_task_runner.py:60} INFO - Started process 3541 to run task
[2025-04-24T21:03:42.539+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'raw_prices_data_downloader_branching', 'branch_TCS.NS', 'manual__2025-04-24T21:03:40.941634+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/raw_price_data_testing.py', '--cfg-path', '/tmp/tmpkr6wd_30']
[2025-04-24T21:03:42.542+0000] {standard_task_runner.py:88} INFO - Job 210: Subtask branch_TCS.NS
[2025-04-24T21:03:42.656+0000] {task_command.py:423} INFO - Running <TaskInstance: raw_prices_data_downloader_branching.branch_TCS.NS manual__2025-04-24T21:03:40.941634+00:00 [running]> on host 8291240c5d79
[2025-04-24T21:03:42.795+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_prices_data_downloader_branching' AIRFLOW_CTX_TASK_ID='branch_TCS.NS' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T21:03:40.941634+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T21:03:40.941634+00:00'
[2025-04-24T21:03:42.800+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 233, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: prices_pipeline.<locals>.branch_condition() missing 1 required positional argument: 'ticker'
[2025-04-24T21:03:42.820+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=raw_prices_data_downloader_branching, task_id=branch_TCS.NS, execution_date=20250424T210340, start_date=20250424T210342, end_date=20250424T210342
[2025-04-24T21:03:42.833+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 210 for task branch_TCS.NS (prices_pipeline.<locals>.branch_condition() missing 1 required positional argument: 'ticker'; 3541)
[2025-04-24T21:03:42.867+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-24T21:03:42.894+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
