[2025-04-24T20:14:25.805+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: raw_prices_data_downloader.fetch_data_testing manual__2025-04-24T20:14:14.802249+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
